### ISSUE TITLE
Emulator check returns true in certain Samsung devices.

### ISSUE THREAD

**Issue by jahirfiquitiva** [javiersantos/PiracyChecker#16] opened 2017-03-13 23:28 UTC
A couple testers have tried the license check in Samsung S7 devices and the license check says they are emulators even when of course they are not.

**Comment by javiersantos** [comment] 2017-03-13 23:48
```Javascript
dependencies {
    compile 'com.github.javiersantos:PiracyChecker:1.0.1'
}
```

**Comment by jahirfiquitiva** [comment] 2017-03-13 23:58
@javiersantos 

I think is actually [this](https://github.com/javiersantos/PiracyChecker/blob/master/library/src/main/java/com/github/javiersantos/piracychecker/LibraryUtils.java#L129) method that is returning true in the Samsung devices (still tested only on an S7).

**Comment by javiersantos** [comment] 2017-03-14 00:02
I was able to reproduce the issue in my device and seems to be fixed within the latest release.

Could you please confirm me if the issue is fixed in the v1.0.1 update?

**Comment by jahirfiquitiva** [comment] 2017-03-14 00:18
@javiersantos 
It will take some time but I will test. I'll let you know as soon as possible.

**Comment by jahirfiquitiva** [comment] 2017-03-14 21:59
@javiersantos 
Sorry for the late response.

The user made some tests and said version 1.0.1 still recognized the device as an emulator.

Disabling emulator check, fixed the issue, so I think it's definitely [this](https://github.com/javiersantos/PiracyChecker/blob/master/library/src/main/java/com/github/javiersantos/piracychecker/LibraryUtils.java#L129) method that is causing the issue, returning true in those Samsung devices.

**Comment by javiersantos** [comment] 2017-03-14 22:53
Thank you for letting me know. I think I have found a workaround based on a third-party library.

**Comment by jahirfiquitiva** [comment] 2017-03-14 22:55
@javiersantos 

Nice, will test it and let you know the results.

Additionally, I would like to mention a check for `Build.MANUFACTURER`, just in case the changes in your last commit do not work.

Will let you know as soon as possible.

Thanks for the help.

**Comment by jahirfiquitiva** [comment] 2017-03-18 03:11
Hi @javiersantos 

I just wanted to let you know that the issue seems to be finally fixed, although I think there's something in the library that is causing a weird crash...

This is all I get from logs:
```
03-17 21:21:57.445 25240-25240/pl.patrykgoworowski.cornieicons I/LibraryChecker: Calling checkLicense on service for pl.patrykgoworowski.cornieicons
03-17 21:21:57.445 25240-25240/pl.patrykgoworowski.cornieicons I/LibraryChecker: Start monitoring timeout.
03-17 21:21:59.746 25240-25283/pl.patrykgoworowski.cornieicons I/LibraryChecker: Received response.
03-17 21:21:59.749 25240-25283/pl.patrykgoworowski.cornieicons I/LibraryChecker: Clearing timeout.
03-17 21:21:59.991 25240-25283/pl.patrykgoworowski.cornieicons A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x674 in tid 25283 (background thre)
                                                                       
                                                                       [ 03-17 21:21:59.995   201:  201 W/         ]
                                                                       debuggerd: handling request: pid=25240 uid=10214 gid=10214 tid=25283
03-17 21:22:00.224 25240-25283/pl.patrykgoworowski.cornieicons A/libc: failed to resend signal during crash: Operation not permitted
```

Could you please look into it? Thanks in advance.

**Comment by jahirfiquitiva** [comment] 2017-03-18 19:13
Here's another set of logs...
```
03-16 19:52:13.564 E/ActivityThread(31710): Activity jahirfiquitiva.iconshowcase.activities.ShowcaseActivity has leaked ServiceConnection com.google.android.vending.licensing.LicenseChecker@3d5b092 that was originally bound here
03-16 19:52:13.564 E/ActivityThread(31710): android.app.ServiceConnectionLeaked: Activity jahirfiquitiva.iconshowcase.activities.ShowcaseActivity has leaked ServiceConnection com.google.android.vending.licensing.LicenseChecker@3d5b092 that was originally bound here
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1093)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:987)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1313)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ContextImpl.bindService(ContextImpl.java:1296)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
03-16 19:52:13.564 E/ActivityThread(31710): 	at com.google.android.vending.licensing.LicenseChecker.checkAccess(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at com.github.javiersantos.piracychecker.PiracyChecker.verify(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at com.github.javiersantos.piracychecker.PiracyChecker.start(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.checkLicense(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.runLicenseChecker(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.onCreate(Unknown Source)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.Activity.performCreate(Activity.java:6251)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.os.Looper.loop(Looper.java:148)
03-16 19:52:13.564 E/ActivityThread(31710): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-16 19:52:13.564 E/ActivityThread(31710): 	at java.lang.reflect.Method.invoke(Native Method)
03-16 19:52:13.564 E/ActivityThread(31710): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-16 19:52:13.564 E/ActivityThread(31710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by javiersantos** [comment] 2017-03-19 10:29
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x674 in tid 25283 (background thre)
                                                                       
                                                                       [ 03-17 21:21:59.995   201:  201 W/         ]
                                                                       debuggerd: handling request: pid=25240 uid=10214 gid=10214 tid=25283
A/libc: failed to resend signal during crash: Operation not permitted
```
I'm not sure it's a library issue since it seems a problem with native C/C++ code. 

```
Activity jahirfiquitiva.iconshowcase.activities.ShowcaseActivity has leaked ServiceConnection com.google.android.vending.licensing.LicenseChecker@3d5b092 that was originally bound here
E/ActivityThread(31710): android.app.ServiceConnectionLeaked: Activity jahirfiquitiva.iconshowcase.activities.ShowcaseActivity has leaked ServiceConnection com.google.android.vending.licensing.LicenseChecker@3d5b092 that was originally bound here
```

This happens because the LVL service is already running but it is called again. I'm working on a fix.

**Closed** 2017-03-19 10:33 UTC
Labels: bug

**Comment by javiersantos** [comment] 2017-03-19 11:35
https://github.com/javiersantos/PiracyChecker/releases/tag/1.0.2
